/// The app's mark, in one place.
///
/// The same painter draws the wordmark on the home screen and the launcher
/// icon generated by `tool/generate_icons.dart`, so the icon on the phone
/// and the logo inside the app can never drift apart.
///
/// What it shows: a grid of cards with one of them singled out. That is
/// literally what the app does — the whole deck is on screen, and the one
/// you are worst at is the one lit up and ringed.
library;

import 'package:flutter/material.dart';

import 'theme.dart';

/// Colours the mark is drawn in.
///
/// Held here rather than read from [BandColor] at paint time so the
/// launcher icon has an explicit, reviewable palette: an icon baked into
/// the APK should not silently change when the in-app bands are retuned.
class MarkColors {
  const MarkColors({
    required this.tile,
    required this.spot,
    required this.ring,
    required this.ground,
  });

  /// The eight cards you are not being asked about.
  final Color tile;

  /// The one you are.
  final Color spot;

  /// The reticle around it.
  final Color ring;

  /// Behind everything, for the launcher icon's own background.
  final Color ground;

  /// The everyday mark: a weak card, in the struggling orange.
  static const MarkColors standard = MarkColors(
    tile: Color(0xFF39404F),
    spot: Color(0xFFC9633C),
    ring: Color(0xFFF5F2E9),
    ground: Color(0xFF15171C),
  );

  /// The Pro mark. Same shape, gold instead of orange — recognisably the
  /// same app, visibly not the same tier.
  static const MarkColors pro = MarkColors(
    tile: Color(0xFF3C3A33),
    spot: Color(0xFFD7A13F),
    ring: Color(0xFFF7EBCF),
    ground: Color(0xFF1B1813),
  );

  /// Gold for "PRO" lettering, bright enough to read on a dark chip.
  static const Color proText = Color(0xFFE0B65A);

  /// Flat white, for Android 13's themed icons, which recolour a
  /// single-tone silhouette to the user's wallpaper.
  static const MarkColors monochrome = MarkColors(
    tile: Color(0x66FFFFFF),
    spot: Color(0xFFFFFFFF),
    ring: Color(0xFFFFFFFF),
    ground: Color(0x00000000),
  );
}

/// Paint the mark to fill [side], with its top-left at the origin.
///
/// Everything is expressed as a fraction of [side], so the same code draws
/// a 20px logo and a 432px icon foreground.
void paintMark(Canvas canvas, double side, MarkColors colors) {
  const columns = 3;
  final gap = side * 0.10;
  final tile = (side - gap * (columns - 1)) / columns;
  final radius = Radius.circular(tile * 0.28);

  final tilePaint = Paint()..color = colors.tile;
  final spotPaint = Paint()..color = colors.spot;

  late Rect centre;
  for (var row = 0; row < columns; row++) {
    for (var column = 0; column < columns; column++) {
      final rect = Rect.fromLTWH(
        column * (tile + gap),
        row * (tile + gap),
        tile,
        tile,
      );
      final isCentre = row == 1 && column == 1;
      if (isCentre) centre = rect;
      canvas.drawRRect(
        RRect.fromRectAndRadius(rect, radius),
        isCentre ? spotPaint : tilePaint,
      );
    }
  }

  // The reticle sits in the gutter around the centre tile. Inflating by
  // less than half the gap keeps it clear of its neighbours at every size,
  // which is what stops the mark turning to mush at 48px.
  final stroke = side * 0.040;
  final reticle = centre.inflate(gap * 0.42);
  canvas.drawRRect(
    RRect.fromRectAndRadius(reticle, Radius.circular(tile * 0.42)),
    Paint()
      ..color = colors.ring
      ..style = PaintingStyle.stroke
      ..strokeWidth = stroke,
  );
}

/// The mark as a widget, for use inside the app.
class WeakspotMark extends StatelessWidget {
  const WeakspotMark({super.key, this.size = 26, this.pro = false});

  final double size;

  /// Draw the Pro mark instead of the everyday one.
  final bool pro;

  @override
  Widget build(BuildContext context) {
    return SizedBox.square(
      dimension: size,
      child: CustomPaint(
        painter: _MarkPainter(pro ? MarkColors.pro : MarkColors.standard),
        isComplex: false,
      ),
    );
  }
}

class _MarkPainter extends CustomPainter {
  const _MarkPainter(this.colors);

  final MarkColors colors;

  @override
  void paint(Canvas canvas, Size size) =>
      paintMark(canvas, size.shortestSide, colors);

  @override
  bool shouldRepaint(_MarkPainter old) => old.colors != colors;
}

/// The wordmark: the mark, the name, and the line under it.
///
/// Pro changes the mark's colour and adds a badge. Nothing else moves, so
/// the header does not reflow when a subscription starts or ends.
class Wordmark extends StatelessWidget {
  const Wordmark({super.key, required this.pro});

  final bool pro;

  @override
  Widget build(BuildContext context) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        WeakspotMark(size: 30, pro: pro),
        const SizedBox(width: 11),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: [
              Row(
                children: [
                  const Flexible(
                    child: Text(
                      'Weakspot',
                      style: TextStyle(
                        fontSize: 23,
                        fontWeight: FontWeight.w700,
                        letterSpacing: -0.4,
                        color: Palette.text,
                      ),
                    ),
                  ),
                  if (pro) ...[
                    const SizedBox(width: 7),
                    const ProBadge(),
                  ],
                ],
              ),
              const SizedBox(height: 2),
              const Text(
                'Everything stays on this device',
                style: TextStyle(fontSize: 12, color: Palette.dim),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

/// The small gold "PRO" tag.
class ProBadge extends StatelessWidget {
  const ProBadge({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
      decoration: BoxDecoration(
        color: const Color(0xFF2E2718),
        borderRadius: BorderRadius.circular(5),
        border: Border.all(color: const Color(0xFF6A5628)),
      ),
      child: const Text(
        'PRO',
        style: TextStyle(
          fontFamily: monoFamily,
          fontSize: 10,
          fontWeight: FontWeight.w700,
          letterSpacing: 0.8,
          color: MarkColors.proText,
        ),
      ),
    );
  }
}
