/// Draws the launcher icon from the same painter the app uses.
///
/// Run it like a test, because that is the cheapest way to get a real
/// canvas without adding an image package to a project that ships no
/// network calls and few dependencies:
///
/// ```bash
/// flutter test tool/generate_icons.dart
/// ```
///
/// It rewrites `android/app/src/main/res`, so the PNGs in git are always
/// reproducible from `lib/ui/logo.dart` — there is no hand-drawn asset to
/// fall out of step with the mark inside the app.
library;

import 'dart:io';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:weakspot/ui/logo.dart';

/// Where Android keeps its icons, and at what pixel size per bucket.
const Map<String, int> _launcherSizes = {
  'mdpi': 48,
  'hdpi': 72,
  'xhdpi': 96,
  'xxhdpi': 144,
  'xxxhdpi': 192,
};

/// An adaptive icon layer is 108dp, of which only the middle 72dp is
/// guaranteed visible once the launcher masks it.
const Map<String, int> _adaptiveSizes = {
  'mdpi': 108,
  'hdpi': 162,
  'xhdpi': 216,
  'xxhdpi': 324,
  'xxxhdpi': 432,
};

/// Share of a legacy icon the mark takes up. The rest is breathing room —
/// a mark pushed to the edges reads as cramped beside other icons.
const double _legacyMarkShare = 0.58;

/// Share of the 108dp adaptive canvas the mark takes up.
///
/// 0.44 keeps it inside the 72dp safe zone with room to spare, so a
/// circular mask never clips the reticle.
const double _adaptiveMarkShare = 0.44;

const String _res = 'android/app/src/main/res';

void main() {
  test('writes every launcher icon', () async {
    for (final entry in _launcherSizes.entries) {
      await _write(
        '$_res/mipmap-${entry.key}/ic_launcher.png',
        await _legacyIcon(entry.value, MarkColors.standard),
      );
    }

    for (final entry in _adaptiveSizes.entries) {
      await _write(
        '$_res/mipmap-${entry.key}/ic_launcher_foreground.png',
        await _layer(entry.value, MarkColors.standard),
      );
      await _write(
        '$_res/mipmap-${entry.key}/ic_launcher_monochrome.png',
        await _layer(entry.value, MarkColors.monochrome),
      );
    }

    await _writeText('$_res/mipmap-anydpi-v26/ic_launcher.xml', _adaptiveXml);
    await _writeText('$_res/values/ic_launcher_background.xml', _backgroundXml);

    // Proof the files are real images and not zero-byte stubs.
    final written = File('$_res/mipmap-xxxhdpi/ic_launcher.png');
    expect(written.existsSync(), isTrue);
    expect(written.lengthSync(), greaterThan(500));
  });
}

/// The pre-Android-8 icon: the mark on its own rounded ground.
Future<Uint8List> _legacyIcon(int side, MarkColors colors) =>
    _render(side, (canvas) {
      final size = side.toDouble();
      canvas.drawRRect(
        RRect.fromRectAndRadius(
          Rect.fromLTWH(0, 0, size, size),
          Radius.circular(size * 0.22),
        ),
        Paint()..color = colors.ground,
      );
      _centreMark(canvas, size, size * _legacyMarkShare, colors);
    });

/// One adaptive layer: the mark alone on transparency.
Future<Uint8List> _layer(int side, MarkColors colors) =>
    _render(side, (canvas) {
      final size = side.toDouble();
      _centreMark(canvas, size, size * _adaptiveMarkShare, colors);
    });

void _centreMark(
  Canvas canvas,
  double canvasSide,
  double markSide,
  MarkColors colors,
) {
  final inset = (canvasSide - markSide) / 2;
  canvas.save();
  canvas.translate(inset, inset);
  paintMark(canvas, markSide, colors);
  canvas.restore();
}

Future<Uint8List> _render(int side, void Function(Canvas) paint) async {
  final recorder = ui.PictureRecorder();
  paint(Canvas(recorder));
  final image = await recorder.endRecording().toImage(side, side);
  final data = await image.toByteData(format: ui.ImageByteFormat.png);
  image.dispose();
  return data!.buffer.asUint8List();
}

Future<void> _write(String path, Uint8List bytes) async {
  final file = File(path);
  await file.parent.create(recursive: true);
  await file.writeAsBytes(bytes);
}

Future<void> _writeText(String path, String text) async {
  final file = File(path);
  await file.parent.create(recursive: true);
  await file.writeAsString(text);
}

const String _adaptiveXml = '''
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_icons.dart. Do not edit by hand. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
    <monochrome android:drawable="@mipmap/ic_launcher_monochrome" />
</adaptive-icon>
''';

const String _backgroundXml = '''
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_icons.dart. Do not edit by hand. -->
<resources>
    <color name="ic_launcher_background">#15171C</color>
</resources>
''';
